# This file is a part of MolStat, which is distributed under the Creative
# Commons Attribution-NonCommercial 4.0 International Public License.
# MolStat (c) 2014, Northwestern University.

##
 # @file tests/fit-symmetric-nonresonant.py
 # @brief Test suite for fitting to the symmetric, nonresonant-tunneling model.
 # 
 # @test Test suite for fitting to the symmetric, nonresonant-tunneling model.
 #
 # The data in symmetric-nonresonant.dat was generated by the simulator with
 # the following input
 # @verbatim
 # observable DifferentialConductance 100 linear
 # model TransportJunction
 # 	distribution ef constant 0.
 # 	distribution v constant 0.
 # 	model SymmetricOneSiteChannel
 # 		distribution epsilon normal 3. 0.05
 # 		distribution gamma normal 0.5 0.05
 # 		distribution a constant 0.
 # 	endmodel
 # endmodel
 # trials 100000
 # output electron_transport/tests/symmetric-nonresonant.dat
 # @endverbatim
 #
 # @author Matthew G.\ Reuter
 # @date November 2014

import subprocess
import math

## @cond

process = subprocess.Popen('../../molstat-fitter', stdout=subprocess.PIPE, stdin=subprocess.PIPE, stderr=subprocess.PIPE)
output = process.communicate( \
'SymmetricNonresonant\n' \
'symmetric-nonresonant.dat\n')

# make sure no errors were reported
assert(output[1] == '')

# check the output string
tokens = output[0].split()
assert(tokens[0] == 'Resid')
assert(tokens[1] == '=')
# check the residual -- this is empirical
assert(math.fabs(float(tokens[2]) - 287.) / 287. < 5.e-2)

# check c -- not empirical
cline = tokens[3].split('=')
assert(cline[0] == 'c')
# need to remove the last character (a comma) from the number for the float call
assert(math.fabs(float(cline[1][:-1]) - 60.) / 60. < 5.e-2) #5% relative error

# check d -- not empirical
dline = tokens[4].split('=')
assert(dline[0] == 'd')
# need to remove the last character (a comma) from the number for the float call
assert(math.fabs(float(dline[1][:-1]) - 10.) / 10. < 5.e-2) #5% relative error

# check norm -- this is empirical
normline = tokens[5].split('=')
assert(normline[0] == 'norm')
assert(math.fabs(float(normline[1]) - 567.) / 567. < 5.e-2)

## @endcond
