# This file is a part of MolStat, which is distributed under the Creative
# Commons Attribution-NonCommercial 4.0 International Public License.
# MolStat (c) 2014, Northwestern University.

##
 # @file tests/fit-symmetric-resonant.py
 # @brief Test suite for fitting to the symmetric, resonant-tunneling model.
 # 
 # @test Test suite for fitting to the symmetric, resonant-tunneling model.
 #
 # The data in symmetric-nonresonant.dat was generated by the simulator with
 # the following input
 # @verbatim
 # SymmetricOneSite
 # DifferentialConductance
 # 100000
 # 100 linear
 # EF constant 0.
 # V constant 0.
 # epsilon normal 0. 0.05
 # gamma normal 0.5 0.05
 # a constant 0.
 # @endverbatim
 # Note that bins with zero counts were deleted from the histogram (they cause
 # numerical problems when fitting to the SymmetricResonantFitModel).
 #
 # @author Matthew G.\ Reuter
 # @date September 2014

import subprocess

## @cond

process = subprocess.Popen('../../molstat-fitter', stdout=subprocess.PIPE, stdin=subprocess.PIPE, stderr=subprocess.PIPE)
output = process.communicate( \
'SymmetricResonant\n' \
'symmetric-resonant.dat\n' \
'guess default\n' \
'guess gamma 40. norm 1000.\n' \
'noprint')

# make sure no errors were reported
assert(output[1] == '')

# check the output string
assert(output[0] == \
'Resid = 3.922257e+00\n' \
'gamma=9.8877e+00, norm=8.7814e+02\n')

## @endcond
