# This file is a part of MolStat, which is distributed under the Creative
# Commons Attribution-NonCommercial 4.0 International Public License.
# MolStat (c) 2014, Northwestern University.

##
 # @file tests/fit-asymmetric-resonant.py
 # @brief Test suite for fitting to the asymmetric, resonant-tunneling model.
 # 
 # @test Test suite for fitting to the asymmetric, resonant-tunneling model.
 #
 # The data in symmetric-nonresonant.dat was generated by the simulator with
 # the following input
 # @verbatim
 # AsymmetricOneSiteModel
 # ZeroBias
 # 100000
 # 100 linear
 # 0.
 # gammaL normal 0.5 0.04
 # gammaR normal 0.7 0.04
 # epsilon normal 0.01 0.05
 # @endverbatim
 #
 # @author Matthew G.\ Reuter
 # @date May 2014

import subprocess

## @cond

process = subprocess.Popen('../fitter', stdout=subprocess.PIPE, stdin=subprocess.PIPE, stderr=subprocess.PIPE)
output = process.communicate( \
'AsymmetricResonant\n' \
'asymmetric-resonant.dat\n' \
'noprint')

# make sure no errors were reported
assert(output[1] == '')

# check the output string
assert(output[0] == \
'Resid = 2.759250e+02\n' \
'gammaL=1.7688e+01, gammaR=1.2675e+01, r=7.4176e-01, norm=4.3936e+01\n')

## @endcond
