# This file is a part of MolStat, which is distributed under the Creative
# Commons Attribution-NonCommercial 4.0 International Public License.
# MolStat (c) 2014, Northwestern University.

##
 # @file tests/fit-asymmetric-resonant.py
 # @brief Test suite for fitting to the asymmetric, resonant-tunneling model.
 # 
 # @test Test suite for fitting to the asymmetric, resonant-tunneling model.
 #
 # The data in symmetric-nonresonant.dat was generated by the simulator with
 # the following input
 # @verbatim
 # AsymmetricOneSite
 # DifferentialConductance
 # 100000
 # 100 linear
 # EF constant 0.
 # V constant 0.
 # epsilon normal 0.01 0.05
 # gammal normal 0.5 0.04
 # gammar normal 0.7 0.04
 # a constant 0.
 # @endverbatim
 #
 # @author Matthew G.\ Reuter
 # @date September 2014

import subprocess

## @cond

process = subprocess.Popen('../../molstat-fitter', stdout=subprocess.PIPE, stdin=subprocess.PIPE, stderr=subprocess.PIPE)
output = process.communicate( \
'AsymmetricResonant\n' \
'asymmetric-resonant.dat\n' \
'noprint')

# make sure no errors were reported
assert(output[1] == '')

# check the output string
assert(output[0] == \
'Resid = 2.788663e+02\n' \
'gammaL=1.7799e+01, gammaR=1.2761e+01, r=7.2185e-01, norm=4.3011e+01\n')

## @endcond
